[package]
name = "easy_menu"
version = "0.1.2"
edition = "2021"
license = "MIT"
authors = ["chickencuber"]
repository = "https://github.com/chickencuber/easy_menu"
description = "a crate that adds a simple menu"

[dependencies]
console = "=0.15.8"
