[package]
name = "simple_menu"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["chickencuber"]
repository = "https://github.com/chickencuber/simple_menu"
description = "a crate that adds a simple menu"

[dependencies]
console = "=0.15.8"
